# --- HỆ THỐNG & HIỂN THỊ ---
set -g default-terminal "screen-256color"
set -as terminal-features ",xterm-kitty:RGB"

set -s escape-time 10
set -sg repeat-time 400
set -s focus-events on
set -g status-interval 10

set -g mouse on 		# allow mouse can use in tmux

set -g set-titles on
setw -g automatic-rename on
set -g renumber-windows on
set -g base-index 1
setw -g pane-base-index 1

# Support extendede for neovim
%if #{>=:version,3.2}
set -g extended-keys #{?#{||:#{m/ri:minty|iTerm,#{TERM_PROGRAM}}, #{!=:#{XTERM_VERSION},}},on,off}
%endif

# KEY BINDINGS
# unbind C-b
set -g prefix C-a
bind C-a send-prefix

# slip panel at current path
unbind %
bind '\' split-window -h -c '#{pane_current_path}'
unbind '"'
bind - split-window -v -c '#{pane_current_path}'

# Reload config
bind r source-file ~/.tmux.conf \; display "Reloaded!"

# Resize pane 
bind -r j resize-pane -D 5
bind -r k resize-pane -U 5
bind -r h resize-pane -L 5
bind -r l resize-pane -R 5

bind -r m resize-pane -Z

# --- COPY MODE (VIM STYLE) ---
set-window-option -g mode-keys vi
bind-key -T copy-mode-vi 'v' send -X begin-selection 

# Copy/Paste - KDE (Wayland/X11)
bind-key -T copy-mode-vi 'y' send -X copy-pipe-and-cancel "if [ \"$XDG_SESSION_TYPE\" = \"wayland\" ]; then wl-copy; else xclip -selection clipboard -in; fi"
bind p run "if [ \"$XDG_SESSION_TYPE\" = \"wayland\" ]; then wl-paste --no-newline; else xclip -selection clipboard -out; fi | tmux load-buffer - && tmux paste-buffer"

# Open a note or todo list 
bind -r e split-window -h "nvim ~/Documents/git/scratch/notes_$(date +'%y%m%d%H').md"
bind -r o split-window -h "nvim ~/Documents/git/scratch/todo_$(date +'%y%m%d').md"

# Pomodoro
bind-key b command-prompt -p "Pomodoro (sessions [work break])" \
  "run-shell 'bash ~/dotfiles/tmux/pomocmd.sh %%'"
bind-key 0 run-shell 'bash ~/dotfiles/tmux/pomodoro.sh stop'

# Open nvim at current path
bind -r v split-window -h -c "#{pane_current_path}" "zsh -c 'nvim; exec zsh'"

# --- PLUGINS (TPM) ---
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'catppuccin/tmux#v2.1.2'
set -g @plugin 'tmux-plugins/tmux-cpu'
set -g @plugin 'xamut/tmux-weather'


# Catppuccin theme
set -g @catppuccin_flavor "mocha"
set -g @catppuccin_window_status_style "basic"
set -g window-status-separator ""
set -g @catppuccin_window_current_text "#[bg=#{@thm_mantle}] #{b:pane_current_path}"
set -g status-left "#[bg=#{@thm_green},fg=#{@thm_crust}]#[reverse]█#[noreverse]#S "
set -g status-right-length 100

run ~/.tmux/plugins/tmux/catppuccin.tmux

set -g status-right "#(bash ~/dotfiles/tmux/pomodoro.sh) #(bash ~/dotfiles/tmux/random_note.sh) "
set -agF status-right "#{E:@catppuccin_status_weather}"
set -agF status-right "#{E:@catppuccin_status_cpu}"
#set -agF status-right "#[bg=#{@thm_green},fg=#{@thm_crust}]#[reverse]█#[noreverse]󰘛 "
#set -agF status-right "#[fg=#{@thm_fg},bg=#{@thm_mantle}]  #(~/dotfiles/tmux/ram.sh) "
set -agF status-right "#[bg=#{@thm_green},fg=#{@thm_crust}]#[reverse]█#[noreverse]󰢗 "
set -agF status-right "#[fg=#{@thm_fg},bg=#{@thm_mantle}] %m/%d %H:%M"

# Khởi chạy TPM
run '~/.tmux/plugins/tpm/tpm'

# Fix background transparent
set -g status-bg default
set -g status-style bg=default
