# Font 
font_family JetbraisMono Nerd
Font
font_size 13.0
bold_font auto
italic_font auto

# Force Kitty use icon of font  MesloLGS
symbol_map U+E000-U+E00D,U+E0A0-U+E0A2,U+E0B0-U+E0B3,U+E0C0-U+E0C8,U+E0CA,U+E0CC-U+E0D4,U+E200-U+E2A9,U+E300-U+E3E3,U+E5FA-U+E6B1,U+E700-U+E7C5,U+ED00-U+F2AF,U+F300-U+F32F,U+F400-U+F4A9,U+F500-U+F8FF,U+F000-U+F2E0 MesloLGS NF

# Opacity
background_opacity 0.85
dynamic_background_opacity yes
background_blur 50

# Window config
window_padding_width 10
confirm_os_window_close 0

# Support Ligatures
disable_ligatures never

# Ensure color is accurate when running tmux
term xterm-256color

# Auto turn start tmux in kitty
shell tmux
